/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ICantBeEvilInterface extends utils.Interface {
  contractName: "ICantBeEvil";
  functions: {
    "getLicenseName()": FunctionFragment;
    "getLicenseURI()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getLicenseName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLicenseURI",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getLicenseName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLicenseURI",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ICantBeEvil extends BaseContract {
  contractName: "ICantBeEvil";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICantBeEvilInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getLicenseName(overrides?: CallOverrides): Promise<[string]>;

    getLicenseURI(overrides?: CallOverrides): Promise<[string]>;
  };

  getLicenseName(overrides?: CallOverrides): Promise<string>;

  getLicenseURI(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getLicenseName(overrides?: CallOverrides): Promise<string>;

    getLicenseURI(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getLicenseName(overrides?: CallOverrides): Promise<BigNumber>;

    getLicenseURI(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getLicenseName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLicenseURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
