/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace ERC721Storage {
  export type ContractURIStruct = {
    name: string;
    description: string;
    image: string;
    externalLink: string;
    sellerFeeBasisPoints: string;
    feeRecipient: string;
  };

  export type ContractURIStructOutput = [
    string,
    string,
    string,
    string,
    string,
    string
  ] & {
    name: string;
    description: string;
    image: string;
    externalLink: string;
    sellerFeeBasisPoints: string;
    feeRecipient: string;
  };
}

export declare namespace PixelPoolyStorage {
  export type CharacterStruct = {
    background: BigNumberish;
    head: BigNumberish;
    body: BigNumberish;
    headAcc: BigNumberish;
    bodyAcc: BigNumberish;
    leftAcc: BigNumberish;
    rightAcc: BigNumberish;
  };

  export type CharacterStructOutput = [
    number,
    number,
    number,
    number,
    number,
    number,
    number
  ] & {
    background: number;
    head: number;
    body: number;
    headAcc: number;
    bodyAcc: number;
    leftAcc: number;
    rightAcc: number;
  };
}

export interface PixelPoolyStorageInterface extends utils.Interface {
  contractName: "PixelPoolyStorage";
  functions: {
    "constructContractURI()": FunctionFragment;
    "constructTokenURI(uint256,bytes,bytes)": FunctionFragment;
    "erc721ImageSignal()": FunctionFragment;
    "erc721Instance()": FunctionFragment;
    "getCharacter(uint256)": FunctionFragment;
    "getContractDescription()": FunctionFragment;
    "getImageBytes(uint256)": FunctionFragment;
    "getPreview(uint256,address)": FunctionFragment;
    "getStore()": FunctionFragment;
    "getSvgRender()": FunctionFragment;
    "getTraitsBytes(uint256)": FunctionFragment;
    "getTraitsFetch()": FunctionFragment;
    "isItemSlotActive(uint256,uint8,uint8)": FunctionFragment;
    "owner()": FunctionFragment;
    "pixelStoreInstance()": FunctionFragment;
    "render(bytes)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setContractURI((string,string,string,string,string,string))": FunctionFragment;
    "setERC721KInstance(address)": FunctionFragment;
    "setPixelStoreInstance(address)": FunctionFragment;
    "setPositionSlot(uint256,uint8,uint8)": FunctionFragment;
    "setSvgRender(address)": FunctionFragment;
    "setTraitsFetch(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "constructContractURI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "constructTokenURI",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "erc721ImageSignal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "erc721Instance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCharacter",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractDescription",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getImageBytes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPreview",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "getStore", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSvgRender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTraitsBytes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTraitsFetch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isItemSlotActive",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pixelStoreInstance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "render", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setContractURI",
    values: [ERC721Storage.ContractURIStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setERC721KInstance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPixelStoreInstance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPositionSlot",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSvgRender",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTraitsFetch",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "constructContractURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "constructTokenURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "erc721ImageSignal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "erc721Instance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCharacter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImageBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPreview", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSvgRender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTraitsBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTraitsFetch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isItemSlotActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pixelStoreInstance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "render", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContractURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setERC721KInstance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPixelStoreInstance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPositionSlot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSvgRender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTraitsFetch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "ContractURIUpdated(tuple)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "SvgRenderUpdated(address)": EventFragment;
    "TraitsFetchUpdated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContractURIUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SvgRenderUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TraitsFetchUpdated"): EventFragment;
}

export type ContractURIUpdatedEvent = TypedEvent<
  [ERC721Storage.ContractURIStructOutput],
  { contractURI: ERC721Storage.ContractURIStructOutput }
>;

export type ContractURIUpdatedEventFilter =
  TypedEventFilter<ContractURIUpdatedEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type SvgRenderUpdatedEvent = TypedEvent<[string], { svgRender: string }>;

export type SvgRenderUpdatedEventFilter =
  TypedEventFilter<SvgRenderUpdatedEvent>;

export type TraitsFetchUpdatedEvent = TypedEvent<
  [string],
  { traitsFetch: string }
>;

export type TraitsFetchUpdatedEventFilter =
  TypedEventFilter<TraitsFetchUpdatedEvent>;

export interface PixelPoolyStorage extends BaseContract {
  contractName: "PixelPoolyStorage";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PixelPoolyStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    constructContractURI(
      overrides?: CallOverrides
    ): Promise<[string] & { uri: string }>;

    constructTokenURI(
      tokenId: BigNumberish,
      input0: BytesLike,
      input1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { uri: string }>;

    erc721ImageSignal(overrides?: CallOverrides): Promise<[string]>;

    erc721Instance(overrides?: CallOverrides): Promise<[string]>;

    getCharacter(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[PixelPoolyStorage.CharacterStructOutput]>;

    getContractDescription(
      overrides?: CallOverrides
    ): Promise<[ERC721Storage.ContractURIStructOutput]>;

    getImageBytes(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPreview(
      tokenId: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getStore(overrides?: CallOverrides): Promise<[string]>;

    getSvgRender(overrides?: CallOverrides): Promise<[string]>;

    getTraitsBytes(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTraitsFetch(overrides?: CallOverrides): Promise<[string]>;

    isItemSlotActive(
      tokenId: BigNumberish,
      position: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pixelStoreInstance(overrides?: CallOverrides): Promise<[string]>;

    render(input: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setContractURI(
      contractURI: ERC721Storage.ContractURIStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setERC721KInstance(
      _erc721Instance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPixelStoreInstance(
      _pixelStoreInstance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPositionSlot(
      tokenId: BigNumberish,
      position: BigNumberish,
      slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSvgRender(
      svgRender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTraitsFetch(
      traitsFetch: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  constructContractURI(overrides?: CallOverrides): Promise<string>;

  constructTokenURI(
    tokenId: BigNumberish,
    input0: BytesLike,
    input1: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  erc721ImageSignal(overrides?: CallOverrides): Promise<string>;

  erc721Instance(overrides?: CallOverrides): Promise<string>;

  getCharacter(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<PixelPoolyStorage.CharacterStructOutput>;

  getContractDescription(
    overrides?: CallOverrides
  ): Promise<ERC721Storage.ContractURIStructOutput>;

  getImageBytes(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getPreview(
    tokenId: BigNumberish,
    account: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getStore(overrides?: CallOverrides): Promise<string>;

  getSvgRender(overrides?: CallOverrides): Promise<string>;

  getTraitsBytes(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getTraitsFetch(overrides?: CallOverrides): Promise<string>;

  isItemSlotActive(
    tokenId: BigNumberish,
    position: BigNumberish,
    slot: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  pixelStoreInstance(overrides?: CallOverrides): Promise<string>;

  render(input: BytesLike, overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setContractURI(
    contractURI: ERC721Storage.ContractURIStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setERC721KInstance(
    _erc721Instance: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPixelStoreInstance(
    _pixelStoreInstance: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPositionSlot(
    tokenId: BigNumberish,
    position: BigNumberish,
    slot: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSvgRender(
    svgRender: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTraitsFetch(
    traitsFetch: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    constructContractURI(overrides?: CallOverrides): Promise<string>;

    constructTokenURI(
      tokenId: BigNumberish,
      input0: BytesLike,
      input1: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    erc721ImageSignal(overrides?: CallOverrides): Promise<string>;

    erc721Instance(overrides?: CallOverrides): Promise<string>;

    getCharacter(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PixelPoolyStorage.CharacterStructOutput>;

    getContractDescription(
      overrides?: CallOverrides
    ): Promise<ERC721Storage.ContractURIStructOutput>;

    getImageBytes(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getPreview(
      tokenId: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getStore(overrides?: CallOverrides): Promise<string>;

    getSvgRender(overrides?: CallOverrides): Promise<string>;

    getTraitsBytes(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getTraitsFetch(overrides?: CallOverrides): Promise<string>;

    isItemSlotActive(
      tokenId: BigNumberish,
      position: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    pixelStoreInstance(overrides?: CallOverrides): Promise<string>;

    render(input: BytesLike, overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setContractURI(
      contractURI: ERC721Storage.ContractURIStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setERC721KInstance(
      _erc721Instance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPixelStoreInstance(
      _pixelStoreInstance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPositionSlot(
      tokenId: BigNumberish,
      position: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setSvgRender(svgRender: string, overrides?: CallOverrides): Promise<void>;

    setTraitsFetch(
      traitsFetch: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ContractURIUpdated(tuple)"(
      contractURI?: null
    ): ContractURIUpdatedEventFilter;
    ContractURIUpdated(contractURI?: null): ContractURIUpdatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "SvgRenderUpdated(address)"(svgRender?: null): SvgRenderUpdatedEventFilter;
    SvgRenderUpdated(svgRender?: null): SvgRenderUpdatedEventFilter;

    "TraitsFetchUpdated(address)"(
      traitsFetch?: null
    ): TraitsFetchUpdatedEventFilter;
    TraitsFetchUpdated(traitsFetch?: null): TraitsFetchUpdatedEventFilter;
  };

  estimateGas: {
    constructContractURI(overrides?: CallOverrides): Promise<BigNumber>;

    constructTokenURI(
      tokenId: BigNumberish,
      input0: BytesLike,
      input1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    erc721ImageSignal(overrides?: CallOverrides): Promise<BigNumber>;

    erc721Instance(overrides?: CallOverrides): Promise<BigNumber>;

    getCharacter(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getContractDescription(overrides?: CallOverrides): Promise<BigNumber>;

    getImageBytes(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPreview(
      tokenId: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStore(overrides?: CallOverrides): Promise<BigNumber>;

    getSvgRender(overrides?: CallOverrides): Promise<BigNumber>;

    getTraitsBytes(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTraitsFetch(overrides?: CallOverrides): Promise<BigNumber>;

    isItemSlotActive(
      tokenId: BigNumberish,
      position: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pixelStoreInstance(overrides?: CallOverrides): Promise<BigNumber>;

    render(input: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setContractURI(
      contractURI: ERC721Storage.ContractURIStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setERC721KInstance(
      _erc721Instance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPixelStoreInstance(
      _pixelStoreInstance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPositionSlot(
      tokenId: BigNumberish,
      position: BigNumberish,
      slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSvgRender(
      svgRender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTraitsFetch(
      traitsFetch: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    constructContractURI(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    constructTokenURI(
      tokenId: BigNumberish,
      input0: BytesLike,
      input1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    erc721ImageSignal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    erc721Instance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCharacter(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getContractDescription(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getImageBytes(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPreview(
      tokenId: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStore(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSvgRender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTraitsBytes(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTraitsFetch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isItemSlotActive(
      tokenId: BigNumberish,
      position: BigNumberish,
      slot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pixelStoreInstance(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    render(
      input: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setContractURI(
      contractURI: ERC721Storage.ContractURIStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setERC721KInstance(
      _erc721Instance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPixelStoreInstance(
      _pixelStoreInstance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPositionSlot(
      tokenId: BigNumberish,
      position: BigNumberish,
      slot: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSvgRender(
      svgRender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTraitsFetch(
      traitsFetch: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
