/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { IDataStream } from "./IDataStream";
export type { IMetaFetch } from "./IMetaFetch";
export type { ISVGModule } from "./ISVGModule";
export type { ISVGRender } from "./ISVGRender";
export type { ITraitsFetch } from "./ITraitsFetch";
export type { Svg } from "./Svg";
export type { SVGColor } from "./SVGColor";
export type { SVGLibrary } from "./SVGLibrary";
export type { SVGRegistry } from "./SVGRegistry";

export { Ownable__factory } from "./factories/Ownable__factory";
export { IDataStream__factory } from "./factories/IDataStream__factory";
export { IMetaFetch__factory } from "./factories/IMetaFetch__factory";
export { ISVGModule__factory } from "./factories/ISVGModule__factory";
export { ISVGRender__factory } from "./factories/ISVGRender__factory";
export { ITraitsFetch__factory } from "./factories/ITraitsFetch__factory";
export { Svg__factory } from "./factories/Svg__factory";
export { SVGColor__factory } from "./factories/SVGColor__factory";
export { SVGLibrary__factory } from "./factories/SVGLibrary__factory";
export { SVGRegistry__factory } from "./factories/SVGRegistry__factory";
