/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC721StorageSync,
  IERC721StorageSyncInterface,
} from "../IERC721StorageSync";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "slots",
    outputs: [
      {
        internalType: "uint8[7]",
        name: "",
        type: "uint8[7]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "traits",
    outputs: [
      {
        internalType: "uint8[7]",
        name: "",
        type: "uint8[7]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "validate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC721StorageSync__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721StorageSyncInterface {
    return new utils.Interface(_abi) as IERC721StorageSyncInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721StorageSync {
    return new Contract(address, _abi, signerOrProvider) as IERC721StorageSync;
  }
}
