/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { TwabLib, TwabLibInterface } from "../TwabLib";

const _abi = [
  {
    inputs: [],
    name: "MAX_CARDINALITY",
    outputs: [
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60c4610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80638200d873146038575b600080fd5b603e6052565b604051604991906075565b60405180910390f35b62ffffff81565b600062ffffff82169050919050565b606f816059565b82525050565b6000602082019050608860008301846068565b9291505056fea264697066735822122015b7c41df1ba35fd8d756f14648ab695d47c151b7498e4c8c76c03a9140b847664736f6c634300080f0033";

type TwabLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TwabLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TwabLib__factory extends ContractFactory {
  constructor(...args: TwabLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "TwabLib";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<TwabLib> {
    return super.deploy(overrides || {}) as Promise<TwabLib>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TwabLib {
    return super.attach(address) as TwabLib;
  }
  connect(signer: Signer): TwabLib__factory {
    return super.connect(signer) as TwabLib__factory;
  }
  static readonly contractName: "TwabLib";
  public readonly contractName: "TwabLib";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TwabLibInterface {
    return new utils.Interface(_abi) as TwabLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TwabLib {
    return new Contract(address, _abi, signerOrProvider) as TwabLib;
  }
}
