/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { CREATE3, CREATE3Interface } from "../CREATE3";

const _abi = [
  {
    inputs: [],
    name: "DeploymentFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "InitializationFailed",
    type: "error",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212206d0be48e44b9d34fd0e06fe97d5776ffd9c5ef2d912021d47d26ec1dade610db64736f6c634300080f0033";

type CREATE3ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CREATE3ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CREATE3__factory extends ContractFactory {
  constructor(...args: CREATE3ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "CREATE3";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<CREATE3> {
    return super.deploy(overrides || {}) as Promise<CREATE3>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): CREATE3 {
    return super.attach(address) as CREATE3;
  }
  connect(signer: Signer): CREATE3__factory {
    return super.connect(signer) as CREATE3__factory;
  }
  static readonly contractName: "CREATE3";
  public readonly contractName: "CREATE3";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CREATE3Interface {
    return new utils.Interface(_abi) as CREATE3Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CREATE3 {
    return new Contract(address, _abi, signerOrProvider) as CREATE3;
  }
}
