/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { LibClone, LibCloneInterface } from "../LibClone";

const _abi = [
  {
    inputs: [],
    name: "DeploymentFailed",
    type: "error",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122073a86ccd53a8ca5dd389331af197b5d375fde4d76f70b8b81cc2dffb08ddbcc064736f6c634300080f0033";

type LibCloneConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibCloneConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibClone__factory extends ContractFactory {
  constructor(...args: LibCloneConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "LibClone";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LibClone> {
    return super.deploy(overrides || {}) as Promise<LibClone>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LibClone {
    return super.attach(address) as LibClone;
  }
  connect(signer: Signer): LibClone__factory {
    return super.connect(signer) as LibClone__factory;
  }
  static readonly contractName: "LibClone";
  public readonly contractName: "LibClone";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibCloneInterface {
    return new utils.Interface(_abi) as LibCloneInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibClone {
    return new Contract(address, _abi, signerOrProvider) as LibClone;
  }
}
