/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { LibString, LibStringInterface } from "../LibString";

const _abi = [
  {
    inputs: [],
    name: "HexLengthInsufficient",
    type: "error",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220710cb7010173e85a0ad4d41570083a5f73983d121986cc3a23eca6063a895abb64736f6c634300080f0033";

type LibStringConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibStringConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibString__factory extends ContractFactory {
  constructor(...args: LibStringConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "LibString";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LibString> {
    return super.deploy(overrides || {}) as Promise<LibString>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LibString {
    return super.attach(address) as LibString;
  }
  connect(signer: Signer): LibString__factory {
    return super.connect(signer) as LibString__factory;
  }
  static readonly contractName: "LibString";
  public readonly contractName: "LibString";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibStringInterface {
    return new utils.Interface(_abi) as LibStringInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibString {
    return new Contract(address, _abi, signerOrProvider) as LibString;
  }
}
