/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  SafeMulticallable,
  SafeMulticallableInterface,
} from "../SafeMulticallable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multicall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class SafeMulticallable__factory {
  static readonly abi = _abi;
  static createInterface(): SafeMulticallableInterface {
    return new utils.Interface(_abi) as SafeMulticallableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SafeMulticallable {
    return new Contract(address, _abi, signerOrProvider) as SafeMulticallable;
  }
}
